
package vistas;

import java.awt.Color;
import java.awt.Desktop;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 * Esta clase contiene los créditos de la aplicación
 * @author José Francisco Sánchez Portillo
 */
public class Dialog_AcercaDe extends javax.swing.JDialog {

    /**
     * Constructor
     * @param parent Parámetro que indica quien ha llamado a este Diealog
     * @param modal Parámetro que indica si es modal o no
     */
    public Dialog_AcercaDe(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null); 
        this.setResizable(false); 
        this.setTitle("Acerca de...");
        //this.setDefaultCloseOperation(0);
    }
    
    public void LinkURL(String link) throws URISyntaxException, IOException{
        Desktop enlace=Desktop.getDesktop();
        try {
                enlace.browse(new URI(link));
        } catch (IOException | URISyntaxException e) {
            e.getMessage();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel_Autor = new javax.swing.JLabel();
        jLabel_Licencia = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel_Agra01 = new javax.swing.JLabel();
        jLabel_Agra02 = new javax.swing.JLabel();
        jLabel_Agra03 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel_Autor.setText("José Francisco Sánchez Portillo");
        jLabel_Autor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_AutorMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_AutorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_AutorMouseExited(evt);
            }
        });

        jLabel_Licencia.setText("Licencia de Creative Commons Reconocimiento-NoComercial-CompartirIgual 4.0 Internacional.");
        jLabel_Licencia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_LicenciaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_LicenciaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_LicenciaMouseExited(evt);
            }
        });

        jLabel3.setText("Licencia: ");

        jLabel4.setText("Autor: ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_Licencia, javax.swing.GroupLayout.DEFAULT_SIZE, 548, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel_Autor, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Licencia)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Autor)
                    .addComponent(jLabel4))
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("La Cena de los Filósofos - DAM (PSP) - IES Aguadulce (Almería):");

        jLabel2.setText("Agradecimientos: ");

        jLabel_Agra01.setText("Wikipedia");
        jLabel_Agra01.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_Agra01MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_Agra01MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_Agra01MouseExited(evt);
            }
        });

        jLabel_Agra02.setText("Academia Usero Estepona");
        jLabel_Agra02.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_Agra02MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_Agra02MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_Agra02MouseExited(evt);
            }
        });

        jLabel_Agra03.setText("Netsis");
        jLabel_Agra03.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_Agra03MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_Agra03MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_Agra03MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel_Agra01, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel_Agra03)
                                    .addComponent(jLabel_Agra02, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 212, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel_Agra01)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_Agra02)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_Agra03)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel_AutorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_AutorMouseEntered
        // TODO add your handling code here:
        this.jLabel_Autor.setForeground(Color.BLUE);
    }//GEN-LAST:event_jLabel_AutorMouseEntered

    private void jLabel_AutorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_AutorMouseExited
        // TODO add your handling code here:
        this.jLabel_Autor.setForeground(Color.BLACK);
    }//GEN-LAST:event_jLabel_AutorMouseExited

    private void jLabel_AutorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_AutorMouseClicked
        try {
            // TODO add your handling code here:
            this.LinkURL("https://pacoportillo.es");
        } catch (URISyntaxException ex) {
            Logger.getLogger(Dialog_AcercaDe.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Dialog_AcercaDe.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabel_AutorMouseClicked

    private void jLabel_LicenciaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_LicenciaMouseEntered
        // TODO add your handling code here:
        this.jLabel_Licencia.setForeground(Color.BLUE);
    }//GEN-LAST:event_jLabel_LicenciaMouseEntered

    private void jLabel_LicenciaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_LicenciaMouseExited
        // TODO add your handling code here:
        this.jLabel_Licencia.setForeground(Color.BLACK);
    }//GEN-LAST:event_jLabel_LicenciaMouseExited

    private void jLabel_LicenciaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_LicenciaMouseClicked
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            this.LinkURL("https://creativecommons.org/licenses/by-nc-sa/4.0/");
        } catch (URISyntaxException ex) {
            Logger.getLogger(Dialog_AcercaDe.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Dialog_AcercaDe.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabel_LicenciaMouseClicked

    private void jLabel_Agra01MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_Agra01MouseEntered
        // TODO add your handling code here:
        this.jLabel_Agra01.setForeground(Color.BLUE);
    }//GEN-LAST:event_jLabel_Agra01MouseEntered

    private void jLabel_Agra01MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_Agra01MouseExited
        // TODO add your handling code here:
        this.jLabel_Agra01.setForeground(Color.BLACK);
    }//GEN-LAST:event_jLabel_Agra01MouseExited

    private void jLabel_Agra01MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_Agra01MouseClicked
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            this.LinkURL("https://es.wikipedia.org/wiki/Problema_de_la_cena_de_los_fil%C3%B3sofos");
        } catch (URISyntaxException ex) {
            Logger.getLogger(Dialog_AcercaDe.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Dialog_AcercaDe.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabel_Agra01MouseClicked

    private void jLabel_Agra02MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_Agra02MouseEntered
        // TODO add your handling code here:
        this.jLabel_Agra02.setForeground(Color.BLUE);
    }//GEN-LAST:event_jLabel_Agra02MouseEntered

    private void jLabel_Agra02MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_Agra02MouseExited
        // TODO add your handling code here:
        this.jLabel_Agra02.setForeground(Color.BLACK);
    }//GEN-LAST:event_jLabel_Agra02MouseExited

    private void jLabel_Agra02MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_Agra02MouseClicked
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            this.LinkURL("https://youtu.be/7G1KzKOodao");
        } catch (URISyntaxException ex) {
            Logger.getLogger(Dialog_AcercaDe.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Dialog_AcercaDe.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabel_Agra02MouseClicked

    private void jLabel_Agra03MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_Agra03MouseEntered
        // TODO add your handling code here:
        this.jLabel_Agra03.setForeground(Color.BLUE);
    }//GEN-LAST:event_jLabel_Agra03MouseEntered

    private void jLabel_Agra03MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_Agra03MouseExited
        // TODO add your handling code here:
        this.jLabel_Agra03.setForeground(Color.BLACK);
    }//GEN-LAST:event_jLabel_Agra03MouseExited

    private void jLabel_Agra03MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_Agra03MouseClicked
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            this.LinkURL("https://netsis.es/cena-filosofos-java/");
        } catch (URISyntaxException ex) {
            Logger.getLogger(Dialog_AcercaDe.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Dialog_AcercaDe.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabel_Agra03MouseClicked



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel_Agra01;
    private javax.swing.JLabel jLabel_Agra02;
    private javax.swing.JLabel jLabel_Agra03;
    private javax.swing.JLabel jLabel_Autor;
    private javax.swing.JLabel jLabel_Licencia;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
